{{- $clusterName := required "clusterName is required. Install with: helm install <RELEASE> . --set clusterName=<YOUR_CLUSTER_NAME>" .Values.clusterName }}
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: {{ $clusterName }}
  namespace: {{ .Values.fleetNamespace | default "fleet-default" }}
  {{- with .Values.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  cloudCredentialSecretName: {{ .Values.cloudCredentialSecretName | quote }}
  kubernetesVersion: {{ .Values.kubernetesVersion | quote }}
  rkeConfig:
    machinePools:
      - name: {{ .Values.controlPool.name }}
        quantity: {{ .Values.controlPool.machineCount }}
        controlPlaneRole: {{ .Values.controlPool.controlPlaneRole }}
        etcdRole: {{ .Values.controlPool.etcdRole }}
        workerRole: {{ .Values.controlPool.workerRole }}
        machineConfigRef:
          kind: {{ .Values.machineConfigKind | default "VmwarevsphereConfig" }}
          apiVersion: {{ .Values.machineConfigApiVersion | default "rke-machine-config.cattle.io/v1" }}
          name: {{ $clusterName }}-control-config
      - name: {{ .Values.workerPool.name }}
        quantity: {{ .Values.workerPool.machineCount }}
        controlPlaneRole: {{ .Values.workerPool.controlPlaneRole }}
        etcdRole: {{ .Values.workerPool.etcdRole }}
        workerRole: {{ .Values.workerPool.workerRole }}
        machineConfigRef:
          kind: {{ .Values.machineConfigKind | default "VmwarevsphereConfig" }}
          apiVersion: {{ .Values.machineConfigApiVersion | default "rke-machine-config.cattle.io/v1" }}
          name: {{ $clusterName }}-worker-config
